databases:
  - name: probiotics
    databaseName: kwepo
    user: kwepo

services:
  - type: web
    name: probiotics
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn probiotics.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kwepo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4