# Generated by Django 4.0.6 on 2023-10-10 03:29

from django.db import migrations, models
import products.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('operating_system', models.CharField(max_length=100, null=True)),
                ('processor', models.CharField(max_length=150, null=True)),
                ('graphics', models.CharField(max_length=150, null=True)),
                ('memory', models.CharField(max_length=150, null=True)),
                ('hard_drive', models.CharField(max_length=150, null=True)),
                ('power_supply', models.CharField(max_length=150, null=True)),
                ('battery', models.CharField(max_length=150, null=True)),
                ('category', models.CharField(choices=[('Laptops', 'Laptops'), ('Tablets', 'Tablets'), ('Phones', 'Phones')], default='Laptops', max_length=150)),
                ('manufacturer', models.CharField(choices=[('HP', 'HP'), ('Acer', 'Acer'), ('Dell', 'Dell'), ('Sony', 'Sony'), ('Apple', 'Apple'), ('Lenovo', 'Lenovo'), ('Techno', 'Techno'), ('Infinix', 'Infinix'), ('Samsung', 'Samsung'), ('Microsoft', 'Microsoft')], default='Apple', max_length=150)),
                ('updated_on', models.DateField(auto_now_add=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
