# Generated by Django 4.0.6 on 2023-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_battery_remove_product_graphics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('Nestle', 'Nestle'), ('Culturelle', 'Culturelle'), ('Solaray', 'Solaray'), ('Innovix Labs', 'InnovixLabs'), ('MegaFood', 'Megafood')], default='Nestle', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=20),
        ),
    ]
